### ISSUE TITLE
Translation library

### ISSUE THREAD

**Issue by Cobra-Mafia** [DineshValor/valor#5]
I would like to know if it is possible to create a translation file. For example in the settings put to load the menu file with the english language.
In the file where the bot settings are, have menu-en.js

**Comment by DineshValor** [comment]
> I would like to know if it is possible to create a translation file. For example in the settings put to load the menu file with the english language. In the file where the bot settings are, have menu-en.js

You can do that, but for that its take to much time to re-write all codes again in every bot single file.

**Comment by DineshValor** [comment]
Thank you for your feedback. Soon Valor Bot will translate into only English version.
