### ISSUE TITLE
Sticker size

### ISSUE THREAD

**Issue by Cobra-Mafia** [DineshValor/valor#6]
I was creating a sticker from an image that I changed its size, instead of creating a sticker in the standard size, I created a smaller sticker and put a white border, instead of the white border could I stretch the image to fill this white border?

**Comment by DineshValor** [comment]
> I was creating a sticker from an image that I changed its size, instead of creating a sticker in the standard size, I created a smaller sticker and put a white border, instead of the white border could I stretch the image to fill this white border?

You can use prefer different modules to create sticker.

**Comment by DineshValor** [comment]
Crop image in square size to fill white border. Bot try to give whole resolution that's why it's fill other remaining portion with white border.
