### ISSUE TITLE
Yt Play 

### ISSUE THREAD

**Issue by SamPandey001** [DineshValor/valor#7]
**Command not working**
Yt audio command is not working please fix it .

**Comment by DineshValor** [comment]
> **Command not working** Yt audio command is not working please fix it .

I'm not sure when get free time to continue this work active. Please give sometime till summer holidays.

**Comment by IkshwakuPande** [comment]
*Plugin:* youtube-ytv.js
*Sender:* 5217661133131@s.whatsapp.net
*Chat:* 120363021985906692@g.us
*Command:* .ytv https://www.youtube.com/watch?v=UbOqsS0swdg yes

Error: Media upload failed on all hosts
    at Object.upload (/app/node_modules/@adiwajshing/baileys/lib/Utils/messages-media.js:467:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /app/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:78:28
    at async Promise.all (index 0)
    at async Object.prepareWAMessageMedia (/app/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:76:40)
    at async Object.generateWAMessageContent (/app/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:227:13)
    at async Object.generateWAMessage (/app/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:349:54)
    at async Object.sendMessage (/app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:397:33)
    at async Object.value [as sendFile] (file:///app/lib/simple.js:198:33) {
  data: null,
  isBoom: true,
  isServer: true,
  output: {
    statusCode: 500,
    payload: {
      statusCode: 500,
      error: 'Internal Server Error',
      message: 'An internal server error occurred'
    },
    headers: {}
  }
}

**Comment by DineshValor** [comment]
> _Plugin:_ youtube-ytv.js _Sender:_ [5217661133131@s.whatsapp.net](mailto:5217661133131@s.whatsapp.net) _Chat:_ [120363021985906692@g.us](mailto:120363021985906692@g.us) _Command:_ .ytv https://www.youtube.com/watch?v=UbOqsS0swdg yes
> 
> Error: Media upload failed on all hosts at Object.upload (/app/node_modules/@adiwajshing/baileys/lib/Utils/messages-media.js:467:19) at runMicrotasks () at processTicksAndRejections (node:internal/process/task_queues:96:5) at async /app/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:78:28 at async Promise.all (index 0) at async Object.prepareWAMessageMedia (/app/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:76:40) at async Object.generateWAMessageContent (/app/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:227:13) at async Object.generateWAMessage (/app/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:349:54) at async Object.sendMessage (/app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:397:33) at async Object.value [as sendFile] (file:///app/lib/simple.js:198:33) { data: null, isBoom: true, isServer: true, output: { statusCode: 500, payload: { statusCode: 500, error: 'Internal Server Error', message: 'An internal server error occurred' }, headers: {} } }

Thanks for you report, will update you soon.

**Comment by Projectwolfdevs** [comment]
yt play no work :(

**Comment by DineshValor** [comment]
> yt play no work :(

🥲

**Comment by DineshValor** [comment]
Can you please provide a screenshot of an error message.

**Comment by DineshValor** [comment]
Youtube downloader fixed.
