### ISSUE TITLE
button can't be used, what should i do?

### ISSUE THREAD

**Issue by Nataslamet** [DineshValor/valor#8]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
![Screenshot_20220620_221801](https://user-images.githubusercontent.com/81040260/174633403-f1beddfb-6d36-4237-a28a-48407cc48950.jpg)
# #

**Comment by DineshValor** [comment]
Investigation start on this issue. Thanx for your feedback.

**Comment by DineshValor** [comment]
In progress, need to modify all plugins.
